#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# default/gen_passwd_sets - 06/14/93
#
# 11/18/2003 - jfs - Check if YPCAT is available before calling it. Also
#        sanity checks for other commands.
#
#-----------------------------------------------------------------------------
#

[ ! -n "$SORT" ] && SORT=`command -v sort`
[ ! -n "$GREP" ] && GREP=`command -v grep`
[ ! -n "$AWK" ] && AWK=`command -v awk`
[ ! -n "$JOIN" ] && JOIN=`command -v join`
[ ! -n "$CAT" ] && CAT=`command -v cat`
[ ! -n "$RM" ] && RM=`command -v rm`
[ ! -n "$SED" ] && SED=`command -v sed`
[ ! -n "$YPCAT" ] && YPCAT=`command -v ypcat`
[ ! -n "$NISCAT" ] && NISCAT=`command -v niscat`
[ ! -n "$WORKDIR" ] && WORKDIR=/tmp

local=0
for parm
do
  case "$parm" in
    -p) ;;
    -l) local=1;;
    *)	outfile="$parm";;
  esac
done

$CAT /etc/passwd > $WORKDIR/etc_passwd.$$
echo "/etc/passwd" > $WORKDIR/etc_passwd.$$.src
echo $WORKDIR/etc_passwd.$$ >> $outfile

[ -n "$YPCAT" ] &&  {
  $YPCAT passwd > $WORKDIR/nis_passwd.$$
  echo "NIS" > $WORKDIR/nis_passwd.$$.src
  echo $WORKDIR/nis_passwd.$$ >> $outfile
}
