#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# tigexp  - 06/13/93
# tigexp  - 05/23/2003 - changed so that it is managed by autoconf
# tigexp  - 11/27/2008 - Proper handling of errors and existance (or
#                        lack of) idx file. Also, regenerate the index
#                        file only if running as root.
# tigexp  - 04/25/2009 - proper wording for error messages
# tigexp  - 10/07/2026 - atrimbitas - Explanations are read from meta/<id>,
#                        one file per finding id with its severity,
#                        category and the checks that report it, instead
#                        of doc/*.txt through an index that had to be
#                        rebuilt as root. Shown as written, not through
#                        fmt, which ran indented examples together. Also
#                        run as "tigris explain".
#
# This program retrieves information explaining what a given message 
# (INFO, WARN, ALERT, FAIL or ERROR) given out by Tiger means.
#
#-----------------------------------------------------------------------------
TigerInstallDir="."

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}
findbase=1

for parm
do
   case $parm in
   -B) basedir=$2; findbase=0; break;;
   esac
done

#
# Routines for verifying environment
#
# haveallcmds - verify command variables
# haveallfiles - verify files
# haveallvars - verify variables
#
haveallcmds()
{
  __retval=0

  for __file
  do
    eval __cmdstr=\$$__file
    set X $__cmdstr
    __cmd=$2
    if [ ! -n "$__cmdstr" ]; then
      echo "--ERROR-- [init001e] Don't have a value for required command $__file."
      __retval=1
    elif [ ! -f "$__cmd" ]; then
      echo "--ERROR-- [init004e] \`$__cmd' is not executable (command $__file)."
      __retval=1
    fi
  done
  return $__retval
}

haveallfiles()
{
  __retval=0

  for __var
  do
    eval __file=\$$__var
    if [ ! -n "$__file" ]; then
      echo "--ERROR-- [init005e] Don't have a value for required file or directory $__var."
      __retval=1
    elif [ ! -f "$__file" -a ! -d "$__file" ]; then
      echo "--ERROR-- [init006e] \`$__file' does not exist (file or directory $__var)."
      __retval=1
    fi
  done

  return $__retval
}

haveallvars()
{
  __retval=0

  for __var
  do
    eval __val=\$$__var
    if [ ! -n "$__val" ]; then
      echo "--ERROR-- [init007e] Don't have required variable $__var."
      __retval=1
    fi
  done

  return $__retval
}


findcmd()
{
  cmd=$1

  srch=/usr/ucb:/usr/bin:/bin:/etc:/usr/etc
  
  saveifs=$IFS
  IFS=:
  set $srch
  IFS=$saveifs
  for dir
  do
    [ -f $dir/$cmd ] && {
      echo $dir/$cmd
      return
    }
  done
}

GREP=`findcmd grep`
SED=`findcmd sed`
SORT=`findcmd sort`

dirname()
{
  _path="$1"

  saveifs=$IFS
  IFS=/
  set X $_path
  IFS=$saveifs

  shift

  if [ $# -eq 1 ]; then
    _dirname='./'
  else
    _dirname=$1
    shift
    while [ $# -ne 1 ]
    do
      _dirname="$_dirname/$1"
      shift
    done
  fi
  
  echo "$_dirname"
}


[ $findbase -ne 0 ] && {
  if [ ! -d "$basedir/meta" -o ! -d "$basedir/systems" ]; then
    tempdir="`dirname $0`"
    if [ -d "$tempdir/meta" -a -d "$tempdir/systems" ]; then
      basedir="$tempdir"
    elif [ -d ../meta -a -d ../systems ]; then
      basedir=..
    fi
  fi
}

BASEDIR="$basedir"
export BASEDIR

params="$*"

haveallcmds GREP SED SORT || exit 1
haveallfiles BASEDIR || exit 1

# explain ID [long]: the explanation of one finding id; "long" puts its
# severity, category and checks first
explain()
{
  echo
  case "$1" in
    ''|*[!a-z0-9]*) meta= ;;     # an id is letters and digits, nothing else
    *) meta="$BASEDIR/meta/$1" ;;
  esac
  if [ -n "$meta" ] && [ -f "$meta" ]; then
    [ "$2" = long ] && {
      $SED -n -e '/^$/q' -e '/^Id:/d' -e p "$meta"
      echo
    }
    $SED '1,/^$/d' "$meta"
  else
    echo "Can not find explanation for message-id $1"
  fi
  echo
}

explainfile()
{
  file=$1
  if [ ! -r "$file" ] ; then
    echo "Error: Cannot read file provided as argument: $file"
    exit 1
  fi
  $GREP '^--[A-Z]*-- \[.*\]' $file |
  $SED -e 's/^.*\[\(.*\)\].*$/\1/' |
  $SORT -u |
  while read msgid
  do
    echo "Message ID: $msgid"
    explain "$msgid" long
  done
}

explaininsert()
{
  file=$1
  msgid=
  [ -f "$file" ] &&  {
  {
    while read line
    do
      case "$line" in
	--[A-Z]*)
	[ -n "$msgid" ] && {
	  explain "$msgid"
	  msgid=
	}
	msgid="`echo \"$line\" | $SED -e 's/^.*\[\(.*\)\].*$/\1/' -e '/\-/d'`"
	;;
	\#*)
	[ -n "$msgid" ] && {
	  explain "$msgid"
	  msgid=
	};;
      esac
      echo "$line"
    done

    [ -n "$msgid" ] && {
      explain "$msgid"
    }
  } < $file
  }
}

set x $params

shift

if [ "$1" = "-f" ]; then
  explainfile $2
elif [ "$1" = "-F" ]; then
  explaininsert $2
elif [ $# -eq 0 ]; then
  echo "Usage: tigris explain ID... (or tigexp ID...), e.g. tigris explain lin002i"
  echo "       tigexp -f REPORT   the explanation of every finding in a report"
  echo "       tigexp -F REPORT   the report with each explanation after its finding"
  exit 1
elif [ $# -eq 1 ]; then
  explain "$1" long
else
  for msg
  do
    echo "[$msg]"
    explain $msg long
  done
fi
