#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# Linux/2/check - 08/12/2002
# 
# Checks for Linux systems
# 
# Linux/2/check - 10/15/2003 - jfs - Removed bashishm (Debian bug #215896)
# Linux/2/check - 04/23/2003 - jfs
# 	Removed CC dependancy, added TODO
#       Debian specific checks moved into an if and check.tbl cleared
#       (that file should be user-only)
# Linux/2/check - 05/09/2003 - jfs
# 	Removed ambiguous redirect
#       Fixed SCRIPTDIR to SYSTEMDIR
# Linux/2/check - 06/26/2003 - jfs
#       Commented out the first call to CHECK_PATCH since it is done
#       only if running on Debian GNU/Linux
# Linux/2/check - 08/28/2003 - jfs
#       Removed Debian specific checks from header since they are
#       already called for below
# Linux/2/check - 04/02/2018 - jfs
#       Make it possible to enable/disable the Debian specific checks
#       based on patch provided by Nicholas Bamber (Debian bug 512085)
# Linux/2/check - 04/02/2018 - jfs
#       Removed deb_checkadvisories as, since 2005, the website does 
#       not include sufficient information to check the package version
#       and generate a proper 'debian_advisories' file
# Tigris: offline
#   Under --root it runs: it only starts the Linux checks, which decide for themselves.
#
#-----------------------------------------------------------------------------
# TODO:
#
# - Nothing yet :)
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds CAT GREP RM SGREP STRINGS || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

haveallcmds CAT GREP RM SGREP STRINGS || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

SYSTEMDIR=$BASEDIR/systems/Linux/2
#
# The following scripts have been added to provide new checks 
# for any Linux system, written by Paul Telford and
# Javier Fernandez-Sanguino
# 
# Note: cannot echo TIMECMD since we lose the handle to the tmplog


[ "$Tiger_Check_SINGLE" != 'N' ] && {
#  echo "`$TIMECMD`> Checking for single user mode password..."
  skip_check $SYSTEMDIR/check_single || $SYSTEMDIR/check_single
}

[ "$Tiger_Check_BOOT" != 'N' ] && {
#  echo "`$TIMECMD`> Checking boot loader file permissions..."
  skip_check $SYSTEMDIR/check_lilo || $SYSTEMDIR/check_lilo
}


[ "$Tiger_Check_RCUMASK" != 'N' ] && {
#  echo "`$TIMECMD`> Checking umask definitions..."
  skip_check $SYSTEMDIR/check_rcumask || $SYSTEMDIR/check_rcumask
}

[ "$Tiger_Check_NEVERLOG" != 'N' ] && {
#  echo "`$TIMECMD`> Checking for users which have not logged in..."
  skip_check $SYSTEMDIR/check_neverlogin || $SYSTEMDIR/check_neverlogin
}

[ "$Tiger_Check_NETWORKCONFIG" != 'N' ] && {
# echo "`$TIMECMD`> Checking for values of the network configuration."
  skip_check $SYSTEMDIR/check_network_config || $SYSTEMDIR/check_network_config
}

[ "$Tiger_Check_SYSCTL" != 'N' ] && {
  skip_check $SYSTEMDIR/check_sysctl || $SYSTEMDIR/check_sysctl
}

[ "$Tiger_Check_SYSTEMD" != 'N' ] && {
  skip_check $SYSTEMDIR/check_systemd || $SYSTEMDIR/check_systemd
}

[ "$Tiger_Check_FIREWALL" != 'N' ] && {
  skip_check $SYSTEMDIR/check_firewall || $SYSTEMDIR/check_firewall
}

[ "$Tiger_Check_SECUREBOOT" != 'N' ] && {
  skip_check $SYSTEMDIR/check_secureboot || $SYSTEMDIR/check_secureboot
}

[ "$Tiger_Check_MAC" != 'N' ] && {
  skip_check $SYSTEMDIR/check_mac || $SYSTEMDIR/check_mac
}

[ "$Tiger_Check_AUDIT" != 'N' ] && {
  skip_check $SYSTEMDIR/check_audit || $SYSTEMDIR/check_audit
}

[ "$Tiger_Check_TIMESYNC" != 'N' ] && {
  skip_check $SYSTEMDIR/check_timesync || $SYSTEMDIR/check_timesync
}

[ "$Tiger_Check_UPDATES" != 'N' ] && {
  skip_check $SYSTEMDIR/check_updates || $SYSTEMDIR/check_updates
}

[ "$Tiger_Check_SUDO" != 'N' ] && {
  skip_check $SYSTEMDIR/check_sudo || $SYSTEMDIR/check_sudo
}

[ "$Tiger_Check_PAM" != 'N' ] && {
  skip_check $SYSTEMDIR/check_pam || $SYSTEMDIR/check_pam
}

[ "$Tiger_Check_UNITS" != 'N' ] && {
  skip_check $SYSTEMDIR/check_units || $SYSTEMDIR/check_units
}

[ "$Tiger_Check_STORAGE" != 'N' ] && {
  skip_check $SYSTEMDIR/check_storage || $SYSTEMDIR/check_storage
}

[ "$Tiger_Check_CONTAINERS" != 'N' ] && {
  skip_check $SYSTEMDIR/check_containers || $SYSTEMDIR/check_containers
}

[ "$Tiger_Check_PASSWD" != 'N' -a "$Tiger_Check_PASSWD_SHADOW" != 'N' ] && {
  skip_check $SYSTEMDIR/check_passwdspec || $SYSTEMDIR/check_passwdspec
}

# The following scripts have been added to provide new checks 
# specific to the Debian system, written by Javier Fernandez-Sanguino
#
[ "$Tiger_Check_PKGINTEGRITY" != 'N' ] && {
  skip_check $SYSTEMDIR/pkg_integrity || $SYSTEMDIR/pkg_integrity
}

if [ "$LXDISTRIBUTION" = "debian" ]; then

# The following checks, for the moment, work only for Debian but
# they could be generalised (there is a tigerrc variable for them)
[ "$Tiger_Check_OS" != 'N' ] && {
#  echo "`$TIMECMD`> Checking for correct OS version..."
  skip_check $SYSTEMDIR/check_release || $SYSTEMDIR/check_release
}

[ "$Tiger_Check_PATCH" != 'N' ] && {
#  echo "`$TIMECMD`> Checking for up-to-date patches..."
  skip_check $SYSTEMDIR/check_patches || $SYSTEMDIR/check_patches
}

# Debian specific checks
[ "$Tiger_Deb_CheckMD5Sums" != 'N' ]&&  {
  skip_check $SYSTEMDIR/deb_checkmd5sums || $SYSTEMDIR/deb_checkmd5sums
}
[ "$Tiger_Deb_NoPackFiles" != 'N' ]&&  {
  skip_check $SYSTEMDIR/deb_nopackfiles || $SYSTEMDIR/deb_nopackfiles
}
[ "$Tiger_Deb_StatOverride" != 'N' ] && {
  skip_check $SYSTEMDIR/deb_statoverride || $SYSTEMDIR/deb_statoverride
}
# End of Debian-specific checks

fi 
