#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2000, 2001 Javier Fernandez-Sanguino Peña
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_listeningprocs - 08/23/2001
#
# 10/07/2026 atrimbitas  Sockets on ports in the kernel's ephemeral range
#                 (ip_local_port_range) are reported once per process,
#                 user, protocol and address, with the ports in the
#                 detail: browsers and Syncthing hold UDP sockets on
#                 ports that change every run, and with the port in the
#                 message each run's findings looked new to tigris-diff
#                 and --since. The lin002i WARN for a listener on every
#                 interface no longer comes with an INFO copy (&& || on
#                 message(), which can return non-zero). Tiger_LSOF_Cmd
#                 lets the tests feed lsof -F fixtures.
# 07/05/2006 jfs  Try not to botch when udp6 services are being read
#                 (Debian Bug #375165)
# 05/15/2005 jfs  Proper check for processes in loopback (Debian Bug #307695)
# 05/02/2004 jfs  Try to avoid eval problems if handling variables with
#                 special characters (such as space)
# 09/19/2003 - jfs - Allow empty okprocess and okprocessuser with the patch
#   provided by Nicolas François. Also added patch improving the 
#   use of NETSTAT and LSOF. Information gathered by both is piped to
#   the same block to generated the report.
#   Reordered changelog.
# 04/23/2003 - jfs - Changed TigerInstallDir to '.'
# 10/16/2002 - jfs - Changed the case statement into an eval in order
#   to properly work for more than two processes or users
#   (i.e. with "process1|process2")
# 04/02/2018 - jfs - Detect if address is in the range 127.0.0.0/8 to 
#    declared it as a loopback address (Savannah bug #24159)
#         
#
# TODO:
# - this script seems to have problems if a program opens an UDP socket
#   expecting a reply from a remote host. This might lead to sockets reported
#   as open spuriously (see Debian Bug#136991). Should this be fixed?
#   (the socket is in fact open and could be accessed remotely)
#
#-----------------------------------------------------------------------------
TigerInstallDir='.'


#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds CUT GREP EGREP || exit 1
# Just netstat is needed to run this program, lsof is an addon
  haveallcmds LSOF || haveallcmds NETSTAT || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  haveallvars TESTLINK HOSTNAME
  
  message CONFIG init003c "" "$0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
echo
echo "# Checking listening processes "

haveallcmds CAT GREP EGREP CUT AWK SED SORT UNIQ || exit 1
[ -n "$Tiger_LSOF_Cmd" ] || haveallcmds LSOF || haveallcmds NETSTAT || exit 1

okprocessusers=${Tiger_Listening_ValidUsers-"root"}
okprocess=${Tiger_Listening_ValidProcs-""}
export okprocess okprocessusers

# Tiger_LSOF_Cmd replaces the lsof call, so the tests can feed it a fixture
lsof_cmd=${Tiger_LSOF_Cmd:-"$LSOF -b -w -FpPcnLt -nPi"}

# The kernel's ephemeral port range. A socket in it was most likely given
# its port by the kernel (browsers, Syncthing and other clients keep UDP
# sockets open on such ports), so the port changes from run to run. Those
# are reported once per process, user, protocol and address, with the
# ports in the detail rather than the message, so that a finding means
# the same thing in two runs and --since does not call it new each time.
set -- `$CAT "${Tiger_Sysctl_Root:-}/proc/sys/net/ipv4/ip_local_port_range" 2>/dev/null`
eph_lo=$1 eph_hi=$2
case "$eph_lo$eph_hi" in ''|*[!0-9]*) eph_lo=32768 eph_hi=60999 ;; esac

[ ! -x "$LSOF" ] && [ -z "$Tiger_LSOF_Cmd" ] && message INFO lin004i "" "Using $NETSTAT instead of lsof, information regarding processes will be more limited"

if [ -x "$LSOF" ] || [ -n "$Tiger_LSOF_Cmd" ]
then
	$AWK -v cmd="$lsof_cmd" '
	BEGIN {

		while ((cmd | getline field) > 0){
			fieldtype = substr(field,1,1)
			sub("^.","",field)
			if      ("p" == fieldtype) {
			}
			else if ("c" == fieldtype) {
				command = field
			}
			else if ("L" == fieldtype) {
				user = field
			}
			else if ("t" == fieldtype) {
				type = field
			}
			else if ("P" == fieldtype) {
				proto = field
			}
			else if ("n" == fieldtype) {
				addr = field
				if (( type == "IPv4" ) && ( addr !~ "->" )) {
					printf ("%s %s %s %s\n", user, proto, addr, command)
				}
			}
		}
		close(cmd)
	}'
else
	$NETSTAT -lpeutw --numeric-hosts --numeric-ports |
	# remove header
	$SED -e '1d;2d' |
	while read type x y local remote listen user inode proc
	do
		[ "$type" = "udp" ] || [ "$type" = "upd6" ] && {
			# there is no listen filed, every field are shifted left
			user=$listen
			proc="$inode $proc"
			type="UDP"
		}

		[ "$type" = "tcp" ] && type="TCP"
		[ "$type" = "tcp6" ] && type="TCP"

		echo $user $type $local "`echo $proc | $CUT -f 2 -d /`"
	done
fi |
# remove duplicates, fold the ephemeral ports of one process, user,
# protocol and address into one line (the ports in the fourth field, "-"
# when there are none), and sort on process
$SORT -u |
$AWK -v lo="$eph_lo" -v hi="$eph_hi" '
{
	# the process name is the rest of the line: it may hold spaces
	rest = $0; sub(/^[^ ]* [^ ]* [^ ]* */, "", rest)
	n = split($3, a, ":"); port = a[n]
	if (port ~ /^[0-9]+$/ && port + 0 >= lo + 0 && port + 0 <= hi + 0) {
		head = $1 " " $2 " " substr($3, 1, length($3) - length(port)) "ephemeral"
		g = head " " rest
		if (!(g in ports)) { order[++ng] = g; heads[g] = head; names[g] = rest }
		ports[g] = ports[g] (ports[g] == "" ? "" : ",") port
	} else
		print $1, $2, $3, "-", rest
}
END { for (i = 1; i <= ng; i++) print heads[order[i]], ports[order[i]], names[order[i]] }' |
$SORT -k 5 |
while read user type asocket ports proc
do
	socket=`echo $asocket |  $CUT -f 2 -d :`
	if [ "$socket" = "ephemeral" ]; then
		socktext="ephemeral ports"
		case "$ports" in *,*) trail="Ports" ;; *) trail="Port" ;; esac
		trail="$trail `echo $ports | $SED 's/,/, /g'`; the kernel gives out $eph_lo-$eph_hi, so they change from run to run."
	else
		socktext="socket $socket"
		trail=""
	fi
	address=`echo $asocket | $CUT -f 1 -d :`
# Should address = 127.0.0.1 be considered harmful?
# TODO: This could be an option
	[ "$address" = "127.0.0.1" ] && address="loopback"
        # Note: Linux loopback is 127.0.0.0/8
        if echo "$address" | $EGREP -q "^127\." ; then
	    address="loopback"
        fi

	[ "$address" = "0.0.0.0" -o "$address" = "*" ] && address="every"
	isokprocess="no"
	isokuser="no"
	# TODO This should change into a function since it's used twice in the
	# code
	[ -n "$okprocess" ] && \
	isokprocess=`eval "case \"$proc\" in ${okprocess})  echo \"yes\" ;; \
	*) echo \"no\" ;; esac"`
	# Probably redundant since this is done already at the top
	[ -n "$okprocessusers" ] && \
	isokuser=`eval "case \"$user\" in ${okprocessusers})  echo \"yes\" ;; \
	*) echo \"no\" ;; esac"`
	if [ "$isokprocess" = "no" ] ; then
		if [ "$isokuser" = "yes" ] ; then
			# an if, not && ||: message() can return non-zero, and
			# the INFO line would then follow every WARN
			if [ "$address" = "every" -a "$Tiger_Listening_Every" != "N" ]; then
				message WARN lin002i "$trail" "The process \`$proc' is listening on $socktext ($type) on $address interface."
			else
				message INFO lin002i "$trail" "The process \`$proc' is listening on $socktext ($type) on $address interface."
			fi
		else
			[ "$address" != "loopback" ]  && {
				message WARN lin003w "$trail" "The process \`$proc' is listening on $socktext ($type on $address interface) is run by $user."
			} 
		fi # of if okuser
	fi # of if okprocess

done 

exit 0 
