#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file COPYING for the complete copyright notice.
#
# SunOS/4/check_cron - 06/14/93
# Linux/2/check_cron - 08/12/2002
# 10/07/2026 - atrimbitas - Look where Debian keeps crontabs too
#     (/var/spool/cron/crontabs: only /var/spool/cron was looked at, so a
#     disabled account's crontab was never found there), and on an offline
#     root (--root) in that root, resolved inside it.
#
# check_cron USER: YES when USER has a crontab, NO otherwise.
#
#-----------------------------------------------------------------------------
#
for f in /var/spool/cron/crontabs/$1 /var/spool/cron/$1
do
  [ -n "$TIGRIS_ROOT" ] &&
    f=`printf '%s\n' "$f" | AWK=${AWK:-awk} sh "$BASEDIR/util/rootpath" "$TIGRIS_ROOT" "$TIGRIS_LINKS"`
  [ -f "$f" ] && { echo "YES"; exit 0; }
done
echo "NO"
