#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# Linux/2/gen_group_sets - 06/14/93 (based on the SunOS)
# 
# 01/15/2004 - jfs - Added some defaults to test the script standalon
#                    and avoid errors when using YPCAT even if its not defined.
#
#-----------------------------------------------------------------------------
#

# If run directly do this, just in case:
[ -z "$GREP" ] && GREP=`command -v grep`
[ -z "$AWK" ] && AWK=`command -v awk`
[ -z "$SED" ] && SED=`command -v sed`
[ -z "$SORT" ] && SORT=`command -v sort`
[ -z "$COMM" ] && COMM=`command -v comm`
[ -z "$RM" ] && RM=`command -v rm`
[ -z "$YPCAT" ] && YPCAT=`command -v ypcat`
[ -z "$WORKDIR" ] && WORKDIR=/tmp


$GREP -v '^[-+]' /etc/group |
$SORT > $WORKDIR/etc_group.$$
echo "/etc/group" > $WORKDIR/etc_group.$$.src
echo $WORKDIR/etc_group.$$

[ -n "$YPCAT" ] && {
  $YPCAT group >$WORKDIR/nis_group.orig.$$ 2>/dev/null
  if [ $? -eq 0 ] ; then
  $SORT < $WORKDIR/nis_group.orig.$$ |
  $AWK '{print substr($0, 1, 255);}' |
  $COMM -23 - $WORKDIR/etc_group.$$ > $WORKDIR/nis_group.$$
  echo "NIS" > $WORKDIR/nis_group.$$.src
  echo $WORKDIR/nis_group.$$
  fi
  # Ypcat has not succeded (ouch), remove the temporary file
  $RM $WORKDIR/nis_group.orig.$$
}

[ "$SERVERCHECK" = "Y" ] && {
  $GETCLIENTDIRS |
  while read client dir
  do
    [ -f "$dir/etc/group" ] && {
      $GREP -v '^[-+]' $dir/etc/group |
      $SORT > $WORKDIR/group.$$.$client
      echo "$client:/etc/group" > $WORKDIR/group.$$.$client.src
      echo $WORKDIR/group.$$.$client
    }
  done
}

