#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# SunOS/4/gen_services - 06/14/93
#
#-----------------------------------------------------------------------------
#

# The file read: this system's, or the offline root's (--root),
# resolved inside it. The set still names it by its own path.
etcfile()
{
  if [ -n "$TIGRIS_ROOT" ]; then
    printf '%s\n' "$1" | AWK=$AWK sh "$BASEDIR/util/rootpath" "$TIGRIS_ROOT" "$TIGRIS_LINKS"
  else
    echo "$1"
  fi
}
SERVICES=`etcfile /etc/services`
$GREP -v '^#' "$SERVICES" |
$SORT > $WORKDIR/etc_services.$$
echo "/etc/services" > $WORKDIR/etc_services.$$.src
echo $WORKDIR/etc_services.$$

