#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 1, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# sub/check_names - 06/14/93
# sub/check_names - jfs - Do not pass untruste input to commands as potential 
#                   options
#
#-----------------------------------------------------------------------------
# This script is not runnable directly.
# 
file="$1"

[ "$CONFIGURED_ALREADY" != "YES" ] && {
  echo "--ERROR-- [init008e] This script can not be run directly."
  exit 1
}

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds LS RM BASENAME || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
echo
echo "# Checking unusual file names..."

haveallcmds LS BASENAME AWK SORT || exit 1

[ -s "$file" ] && {
  # List each file in the system directories named by Tiger_FSScan_DetailDirs;
  # elsewhere (home directories, data disks) odd names are routine and get
  # one line per directory. Same split as find_files uses for dangling links.
  $AWK -v detail="${Tiger_FSScan_DetailDirs-/etc|/bin|/sbin|/lib|/usr/bin|/usr/sbin|/usr/lib|/usr/local|/opt|/boot|/root|/var/lib|/var/spool|/srv}" '
    BEGIN { n = split(detail, prefix, "|") }
    {
      listed = (detail == "*")
      for (i = 1; i <= n && !listed; i++)
        if (index($0, prefix[i]) == 1) listed = 1
      if (listed) { print "D " $0; next }
      split($0, part, "/")
      dir = "/" part[2]
      if (part[4] != "") dir = dir "/" part[3]
      count[dir]++
    }
    END { for (dir in count) print "S " count[dir] " " dir }
  ' "$file" | $SORT |
  while read kind rest
  do
    case $kind in
      D)
	pathname=$rest
	name="`$BASENAME -- \"$pathname\"`"
	case "$name" in
	  .FSP*)
	    message WARN fsys009w "" "FSP server control file found:"
	    $LS $LSGROUP -ld -- "$pathname";;
	  *)
	    message ALERT fsys005a "" "Unusual filename \`$name' found:"
	    $LS $LSGROUP -ld -- "$pathname";;
	esac;;
      S)
	set -- $rest
	message WARN fsys017w "" "$1 files with unusual names under $2 are not listed (see Tiger_FSScan_DetailDirs).";;
    esac
  done
  echo
}
