#!/bin/sh
#
# tests/mail_check.sh - check_mail on offline roots
#
# Five roots: Postfix with AUTH in clear, the world relaying, and
# the default banner; Exim with a plaintext authenticator, a
# wildcard relay, and no banner set (via conf.d fragments); Dovecot
# with plaintext allowed, TLS off, and a versioned greeting; a
# tight root (AUTH under TLS, named relay nets, quiet banners, a
# TLS-gated Exim authenticator); and an empty root, where there is
# no mail and nothing is said. INFO findings only show with
# Tiger_Show_INFO_Msgs=Y. Runs as a user and as root; the fixtures
# read the same for both.
#
TIGER=${TIGER:-`cd "\`dirname \"$0\"\`/.." && pwd`}
W=`mktemp -d`
trap 'rm -rf "$W"' 0
( cd "$TIGER" && tar --exclude=.git --exclude=./log --exclude=./run -cf - . ) | ( cd "$W" && tar -xf - )
mkdir -p "$W/run" "$W/log"
cp "$W/tigerrc" "$W/tigerrc.base"
fail=0
ok()  { echo "ok   $1"; }
bad() { echo "FAIL $1"; fail=1; }
run() {  # run ROOT OUTFILE: check_mail with ROOT as the audited system
  cp "$W/tigerrc.base" "$W/tigerrc"
  { echo "Tiger_Show_INFO_Msgs=Y"; } >> "$W/tigerrc"
  ( cd "$W" && TIGERHOMEDIR=$W TIGRIS_ROOT="$1" sh ./systems/Linux/2/check_mail ) 2>&1 |
  awk '/^--/ { if (l != "") print l; l = $0; next } /^ / { sub(/^ +/, " "); l = l $0; next } { if (l != "") print l; l = "" } END { if (l != "") print l }' |
  tr -s ' ' | grep '^--' | grep -v '^--CONFIG--' > "$2" || true
}
has() { grep -F -q -- "$1" "$2"; }

P=$W/postfix; mkdir -p "$P/etc/postfix"
cat > "$P/etc/postfix/main.cf" <<'EOF'
smtpd_sasl_auth_enable = yes
mynetworks = 127.0.0.0/8 0.0.0.0/0
EOF
run "$P" "$W/out"
has '--WARN-- [mail001w] Postfix offers SMTP AUTH with nothing protecting it' "$W/out" &&
has '--WARN-- [mail002w] Postfix relays for the whole world' "$W/out" &&
has '--INFO-- [mail003i] Postfix advertises its version' "$W/out" &&
  ok "Postfix open on all three: mail001w, mail002w, mail003i" || { bad "postfix"; cat "$W/out"; }

X=$W/exim; mkdir -p "$X/etc/exim4/conf.d/auth" "$X/etc/exim4/conf.d/main" "$X/etc/exim4/conf.d/acl"
cat > "$X/etc/exim4/conf.d/auth/10-login" <<'EOF'
begin authenticators
login:
  driver = plaintext
  public_name = LOGIN
EOF
printf 'hostlist relay_from_hosts = <; localhost ; *\n' > "$X/etc/exim4/conf.d/main/01-relay"
run "$X" "$W/out"
has '--WARN-- [mail001w] Exim offers plaintext AUTH with nothing requiring TLS' "$W/out" &&
has '--WARN-- [mail002w] Exim relays for the whole world' "$W/out" &&
has '--INFO-- [mail003i] Exim advertises its version' "$W/out" &&
  ok "Exim fragments: all three" || { bad "exim"; cat "$W/out"; }

D=$W/dovecot; mkdir -p "$D/etc/dovecot/conf.d"
cat > "$D/etc/dovecot/dovecot.conf" <<'EOF'
!include conf.d/*.conf
disable_plaintext_auth = yes
protocol imap {
  ssl = no
}
EOF
cat > "$D/etc/dovecot/conf.d/10-ssl.conf" <<'EOF'
ssl = no
login_greeting = Dovecot 2.3.21 ready.
EOF
run "$D" "$W/out"
has '--WARN-- [mail001w] Dovecot takes passwords in clear' "$W/out" &&
has '--INFO-- [mail003i] Dovecot advertises its version' "$W/out" &&
  ok "Dovecot plaintext with TLS off: mail001w" || { bad "dovecot"; cat "$W/out"; }

O=$W/blockonly; mkdir -p "$O/etc/dovecot"
cat > "$O/etc/dovecot/dovecot.conf" <<'EOF'
disable_plaintext_auth = yes
ssl = yes
protocol imap {
  ssl = no
}
EOF
run "$O" "$W/out"
grep -q 'mail001w' "$W/out" && { bad "blockonly"; cat "$W/out"; } ||
  ok "ssl=no inside a protocol block only: nothing"

T=$W/tight; mkdir -p "$T/etc/postfix" "$T/etc/exim4" "$T/etc/dovecot"
cat > "$T/etc/postfix/main.cf" <<'EOF'
smtpd_sasl_auth_enable = yes
smtpd_tls_auth_only = yes
mynetworks = 127.0.0.0/8 10.0.0.0/8
smtpd_banner = $myhostname ESMTP
EOF
cat > "$T/etc/exim4/config.autogenerated" <<'EOF'
begin authenticators
login:
  driver = plaintext
  public_name = LOGIN
  server_advertise_condition = ${if eq{$tls_in_cipher}{}{no}{yes}}
hostlist relay_from_hosts = <; localhost
smtp_banner = mail.example.com ESMTP
EOF
cat > "$T/etc/dovecot/dovecot.conf" <<'EOF'
disable_plaintext_auth = yes
ssl = yes
login_greeting = Welcome.
EOF
run "$T" "$W/out"
grep -q 'mail001w\|mail002w\|mail003i' "$W/out" && { bad "tight"; cat "$W/out"; } ||
  ok "AUTH under TLS, named relays, quiet banners, gated Exim: nothing"

E=$W/empty; mkdir -p "$E/etc"
run "$E" "$W/out"
[ -s "$W/out" ] && { bad "empty"; cat "$W/out"; } ||
  ok "no mail config files: nothing said"

[ $fail -eq 0 ] && echo "PASS"
exit $fail
