
[DEFAULT]
# the default branch for upstream sources:
upstream-branch = master
# the default branch for the debian patch:
debian-branch = debian
# the default tag formats used:
upstream-tag = version_%(version)s
debian-tag = debian/1\%%(version)s
debian-tag-msg = %(pkg)s Debian release %(version)s
# don't check if debian-branch == current branch:
ignore-branch = True
