#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2003 Ryan Bradetich
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_ssh - Checks for configuration directives in the SSH configuration
#             file.
#
# 01/07/2004 - rbrad - Applied Savannah Patch: 2439 to make POSIX compliant.
# 11/19/2003 - jfs - This script is not POSIX compliant (yet)
# 09/19/2003 - jfs - Applied patch from Ryan Braderitch fixing typoes (sp?)
# 09/03/2003 - jfs - Removed PermitRootLogin since that's checked by check_root
#             (and belongs there, IMHO) also added failsafe checks for 
#             SSHD_CONFIG which might not be configured in some systems
# 06/30/2003 - rbradetich@uswest.net - first release
#
# TODO:
#   - Add additional directives that can be checked.
#   - Figure out a clever method for integrating the default checks with the
#     normal checks.
#   - Currently suited for OpenSSH needs to be tested with other SSH daemons
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallfiles BASEDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

echo
echo "# Checking sshd_config configuration files..."

haveallfiles BASEDIR || exit 1

#
# Parse the Protocol line and verify only allowed protocols are specified.
# Return 0 if the protocol is not in the approved protocol list, otherwise
# return 1.
#
parse_Protocol()
{
	line=$1

	[ -z "$Tiger_SSH_Protocol" ] && return 1
	while [ -n "$line" ]
	do
		proto=${line%%,*}
		line=${line##${proto}}
		line=${line##,}

		eval "case \"$proto\" in
			$Tiger_SSH_Protocol)
				;;
			*)
				return 0
				;;
		esac"
	done
	return 1
}

#
# Generic parsing routine for SSH Daemon directivies. 
# Return 0 if the value is not in the approved list, otherwise
# return 1.
#
parse_directive()
{
	value=$1
	list=$2

	[ -z "$list" ] && return 1
	eval "case \"$value\" in
		$list)
			return 1
			;;
		*)
			return 0
			;;
	esac"
}

#
# Parse the specified sshd_config file.
#
parse_sshd_config_file()
{
	# Declare some variables to see if specified attributes are specified
	# or if we need to check the defaults.
	found_Protocol=0
	found_RhostsAuthentication=0
	found_PasswordAuthentication=0

	while read line
	do
		line=${line%%\#*}
		key=${line%% *}
		line=${line##${key}}

		case "$key" in
			Protocol)
				found_Protocol=1
				parse_Protocol $line $1 && {
					message WARN ssh001w "" "Protocol $proto is enabled in $file"
				}	
				;;
				
			RhostsAuthentication)
				found_RhostsAuthentication=1
				parse_directive $line $Tiger_SSH_RhostsAuthentication && {
					message WARN ssh003w "" "The RhostsAuthentication directive in $1 is set to the unapproved value: $line."
				}
				;;

			PasswordAuthentication)
				found_PasswordAuthentication=1
				parse_directive $line $Tiger_SSH_PasswordAuthentication && {
					message WARN ssh004w "" "The PasswordAuthentication directive in $1 is set to the unapproved value: $line."
				}
				;;
		esac
	done < $1

	# Check the default values if the entry was not specified.
	[ $found_Protocol = 0 ] && parse_Protocol "2,1" && {
		message WARN ssh001w "" "Protocol $proto is enabled in $file"
	}
	[ $found_RhostsAuthentication = 0 ] && parse_directive "no" $Tiger_SSH_RhostsAuthentication && {
		message WARN ssh003w "" "The RhostsAuthentication directive in $1 is set to the unapproved default value: no."
	}
	[ $found_PasswordAuthentication = 0 ] && parse_directive "yes" $Tiger_SSH_PasswordAuthentication && {
		message WARN ssh004w "" "The PasswordAuthentication directive in $1 is set to the unapproved defult value: yes."
	}
}

# If SSHD_CONFIG is not defined we use some sane values
[ -z "$SSHD_CONFIG" ] && {
if [ -f /usr/local/etc/sshd_config ]; then
  SSHD_CONFIG=/usr/local/etc/sshd_config
elif [ -f /etc/sshd_config ]; then
  SSHD_CONFIG=/etc/sshd_config
elif [ -f /etc/ssh2/sshd2_config ]; then
  SSHD_CONFIG=/etc/ssh2/sshd2_config
elif [ -f /etc/ssh/sshd_config ]; then
  SSHD_CONFIG=/etc/ssh/sshd_config
fi
}

#
# The effective configuration, as sshd itself resolves it: Include files,
# Match-free defaults and all. Needs a working sshd and (for its host keys)
# root; otherwise the text parsing below is used. Tiger_SSHD_Cmd lets the
# tests feed a fixture in sshd -T format.
#
effective=
sshd_cmd=${Tiger_SSHD_Cmd:-}
if [ -z "$sshd_cmd" ]; then
	for d in /usr/sbin /usr/local/sbin /sbin
	do
		[ -x "$d/sshd" ] && { sshd_cmd="$d/sshd -T"; break; }
	done
	# A single configured file that is not the default: ask sshd about that one
	case "$SSHD_CONFIG" in
		''|/etc/ssh/sshd_config|*' '*) ;;
		*) [ -n "$sshd_cmd" ] && sshd_cmd="$sshd_cmd -f $SSHD_CONFIG" ;;
	esac
fi
if [ -n "$sshd_cmd" ]; then
	effective=$WORKDIR/sshd.effective.$$
	safe_temp $effective
	$sshd_cmd 2>/dev/null | $TR 'A-Z' 'a-z' > $effective
	[ -s "$effective" ] || { delete $effective; effective=; }
fi

# Value of one keyword in the effective configuration (lower case)
setting()
{
	$AWK -v k="$1" '$1 == k { $1 = ""; sub(/^ /, ""); print; exit }' $effective
}

if [ -n "$effective" ]; then
	echo "# Checking the effective sshd configuration (sshd -T)..."
	# keyword, test, wanted, level, code, what the wrong value means.
	# 'is' takes a case pattern; 'le' a number the value must not exceed.
	while read key test want level code text
	do
		case "$key" in ''|\#*) continue ;; esac
		value=`setting $key`
		[ -z "$value" ] && continue
		ok=N
		case "$test" in
			is) eval "case \"\$value\" in $want) ok=Y ;; esac" ;;
			le) case "$value" in *[!0-9]*) ok=Y ;; *) [ "$value" -le "$want" ] && ok=Y ;; esac ;;
		esac
		[ "$ok" = N ] && message $level $code "" "sshd: $key is $value: $text"
	done <<EOF
passwordauthentication       is no                                                           WARN ssh004w passwords are accepted for login
permitrootlogin              is no|prohibit-password|without-password|forced-commands-only   FAIL ssh006f root may log in with a password
permitemptypasswords         is no                                                           FAIL ssh007f accounts with an empty password may log in
x11forwarding                is no                                                           WARN ssh008w X11 is forwarded, which exposes the client's display to this server
maxauthtries                 le 4                                                            WARN ssh009w more than four authentication attempts are allowed per connection
usepam                       is yes                                                          WARN ssh010w PAM is bypassed, so its account and session rules do not apply
kbdinteractiveauthentication is no                                                           WARN ssh011w keyboard-interactive login is open, which PAM can turn into a password prompt
logingracetime               le 60                                                           WARN ssh012w an unauthenticated connection may be held open for more than 60 seconds
hostbasedauthentication      is no                                                           WARN ssh013w hosts are trusted on the strength of their host key alone
ignorerhosts                 is yes                                                          WARN ssh014w .rhosts and .shosts files are consulted
permituserenvironment        is no                                                           WARN ssh015w users may set LD_PRELOAD and the like through authorized_keys
loglevel                     is info|verbose|debug|debug1|debug2|debug3                      WARN ssh016w logins are not logged in enough detail to investigate
EOF
	weak=`setting ciphers | $TR ',' '\n' | $GREP -E 'cbc|arcfour|rc4|3des|blowfish|cast128' | $TR '\n' ' '`
	[ -n "$weak" ] && message WARN ssh017w "" "sshd: weak ciphers are enabled: $weak"
	weak=`setting macs | $TR ',' '\n' | $GREP -E 'md5|-96$|-96-etm|ripemd' | $TR '\n' ' '`
	[ -n "$weak" ] && message WARN ssh018w "" "sshd: weak MACs are enabled: $weak"
	weak=`setting kexalgorithms | $TR ',' '\n' | $GREP -E 'diffie-hellman-group1-|diffie-hellman-group14-sha1|group-exchange-sha1' | $TR '\n' ' '`
	[ -n "$weak" ] && message WARN ssh019w "" "sshd: weak key exchange algorithms are enabled: $weak"
	delete $effective
	exit 0
fi

# Main loop, check all the specified sshd_config files.
if [ -n "$SSHD_CONFIG" ] 
then
	for file in $SSHD_CONFIG
	do
		[ -r "$file" ] && parse_sshd_config_file $file
	done
else
	message FAIL ssh005w "" "Cannot find a configuration file for SSH."
fi

exit 0
