#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# check_devices
# 	checks permissions on tape devices
# 10-30-2001
# Paul Telford <paul_telford@hp.com>
#
# 09/19/2003 jfs  Fixed error with patch submitted by Ryan Bradetich
# 08/12/2003 jfs  Fixed error (dirs->dir) and added a warning for 
#                 non-special files.
# 08/11/2003 jfs  Fixed dependancies.
# 04/15/2003 jfs  Fixed stupid error which made terminals appear 
#		  (/dev/ -> /dev)
# 08/12/2002 jfs  Added /devices/pseudo/pts to terminal lists.
# 08/09/2002 jfs  Fixed to work in Solaris (added pseudo devices and changed
#                 -L to -h)
# 07/25/2002 jfs  Changed TigerInstallDir to .
# 10/04/2026 atrimbitas  Tell world-readable (dev004w) from world-writable
#                 (dev002f); excuse the Linux devices that are world-writable
#                 by design (ptmx, fuse, nvidia*), the directories udev and
#                 drivers create today, and any directory that holds only
#                 symlinks (udev alias trees, LVM volume groups)
# 03/31/2005 jfs  Added EXPECTEDIRS and EXPECTEDDEVICES in /dev (Os specific)
#                 and added Solaris (9) devices
# 05/20/2006 jfs  Handle the special case of having " in filenames by quoting
#                 the character (Debian bug #355096)
# 06/21/2007 jfs  Extend the list of EXPECTEDDIRS for Linux to cover udev
# 12/08/2011 jfs  Extend the list of EXPECTEDDIRS to cover /dev/bsg 
#                 (Debian bug #616339)
#                 Do not test symbolic links if they point to regular files.
#                 (Debian bug #616337)
#                 Fix typos in names of variables when defined.
#
#-----------------------------------------------------------------------------
#
# Tigris: offline
#   the root's device directories; every test resolves inside it.
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done
#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}
. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds LS AWK SED || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}
#------------------------------------------------------------------------

haveallcmds LS AWK SED GREP || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

check_dev_file()
{
	device=$1
	getpermit $device |
    	while read filename rowner rgroup rur ruw rux rgr rgw rgx ror row rox rsuid rsgid rstk
    	do
		if [ $row -eq 1 -o $rox -eq 1 ]
		then
		case $device in
		/dev/st[0-9])
			message FAIL dev001f "" "$device has world permissions"
		;;
		*)
			message FAIL dev002f "" "$device has world permissions"
		;;
		esac
		elif [ $ror -eq 1 ]
		then
			message WARN dev004w "" "$device is world readable"
		fi
	done

}

echo
echo "# Checking device permissions..."

EXPECTEDFILES="/dev/none"
if [ "$OS" = "Linux" ] ; then
	EXPECTEDFILES="/dev/core|/dev/stdout"
fi
EXPECTEDDIRS="/dev/none"
if [ "$OS" = "SunOS" ] ; then
	EXPECTEDDIRS="/dev/cfg|/dev/cua|/dev/dsk|/dev/es|/dev/fd|/dev/md|/dev/printers|/dev/pts|/dev/rdsk|/dev/sad|/dev/swap|/dev/term"
fi
if [ "$OS" = "Linux" ] ; then
	EXPECTEDDIRS="/dev/mapper|/dev/net|/dev/shm|/dev/cciss|/dev/fd|/dev/ida|/dev/input|/dev/mapper|/dev/net|/dev/pts|/dev/rd|/dev/shm|/dev/usb|/dev/ataraid|/dev/bus|/dev/cdroms|/dev/discs|/dev/disk|/dev/dri|/dev/fb|/dev/floppy|/dev/i2c|/dev/loop|/dev/md|/dev/misc|/dev/ptal-printd|/dev/scsi|/dev/snd|/dev/sound|/dev/tts|/dev/vc|/dev/vcc|/dev/bsg|/dev/block|/dev/char|/dev/cpu|/dev/dma_heap|/dev/hugepages|/dev/mqueue|/dev/nvidia-caps|/dev/serial|/dev/v4l|/dev/vfio|/dev/zvol|/dev/infiniband|/dev/xen"
fi

dirs="/dev"
# For Solaris but maintain compatibility with others
# (in Solaris /dev/ are symlinks to devices in /devices/pseudo)
[ -d "`__here /devices`" ] && dirs="$dirs /device"
[ -d "`__here /devices/pseudo`" ] && dirs="$dirs /devices/pseudo"
for dir in $dirs
do
# The glob cannot expand on this host when the files live in a root:
# list the root's directory instead (same names the glob would match).
DEVLIST="$dir/[a-z0-9]*"
[ -n "$TIGRIS_ROOT" ] && DEVLIST="`rootls "$dir" | $GREP "^$dir/[a-z0-9]"`"
for file in $DEVLIST
do

	# Expected regular files in these directories are EXPECTEDFILES
	[ ! -h "`__here "$file"`" ] && [ -f "`__here "$file"`" ] &&  {
	  matchlist "$file" "$EXPECTEDFILES" ||
	    message WARN dev003w "" "File $file is a regular file in a device directory."
	}

	# Expected directories are EXPECTEDDIRS. A directory of nothing but
	# symlinks is an alias tree made by udev (/dev/disk/by-*) or LVM
	# (/dev/<volume group>), not a hiding place
	[ -d "`__here "$file"`" ] && {
	  matchlist "$file" "$EXPECTEDDIRS" || {
	    if $LS -lA "`__here "$file"`" | $SED 1d | $GREP -qv '^l' ; then
	      message WARN dev003w "" "The directory $file resides in a device directory."
	    fi
	  }
	}

    	case $file in
	/dev/pty*|/dev/tty*|/devices/pseudo/pts*)
	# Do not check for virtual terminals
	;;
	/dev/urandom|/dev/random|/dev/zero|/dev/full|/dev/null)
	# Same for some special devices
	;;
	/dev/ptmx|/dev/fuse|/dev/nvidia*)
	# World-writable by design on Linux: ptmx hands out pseudo-terminals,
	# fuse is how user file systems are mounted, and NVIDIA's driver
	# opens its nodes to every user
	;;
	/devices/pseudo/mm@0:null|/devices/pseudo/mm@0:zero|/devices/pseudo/random@0:random|/devices/pseudo/random@0:urandom)
	# And for some devices in Solaris
	;;
	*)
	# Do not check directories or symbolic links
		if [ ! -d "`__here "$file"`"  -a  ! -h "`__here "$file"`" ] 
		then
		   check_dev_file $file
		fi
	;;
	esac
done
done

exit 0
