#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 2026 Andrei Trimbitas
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2, or (at your option)
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# FreeBSD/default/check - 10/09/2026
#     The FreeBSD system checks, run by scripts/check_system. Grows
#     as the BSD sides land; tiger-direct shadows are not listed
#     here (listing them would run them twice).
#
#-----------------------------------------------------------------------------
#
TigerInstallDir='.'

#
# Set default base directory.
# Order or preference:
#      -B option
#      TIGERHOMEDIR environment variable
#      TigerInstallDir installed location
#
basedir=${TIGERHOMEDIR:=$TigerInstallDir}

for parm
do
   case $parm in
   -B) basedir=$2; break;;
   esac
done

#
# Verify that a config file exists there, and if it does
# source it.
#
[ ! -r $basedir/config ] && {
  echo "--ERROR-- [init002e] No 'config' file in \`$basedir'."
  exit 1
}

. $basedir/config

. $BASEDIR/initdefs
#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds CAT GREP || exit 1
  haveallfiles BASEDIR WORKDIR || exit 1

  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

haveallcmds CAT GREP || exit 1
haveallfiles BASEDIR WORKDIR || exit 1

SYSTEMDIR=$BASEDIR/systems/FreeBSD/default
#
# Note: cannot echo TIMECMD since we lose the handle to the tmplog

[ "$Tiger_Check_FIREWALL" != 'N' ] && {
  skip_check $SYSTEMDIR/check_firewall || $SYSTEMDIR/check_firewall
}

[ "$Tiger_Check_PROMISC" != 'N' ] && {
  skip_check $SYSTEMDIR/check_promisc || $SYSTEMDIR/check_promisc
}

[ "$Tiger_Check_PKG" != 'N' ] && {
  skip_check $SYSTEMDIR/check_pkg || $SYSTEMDIR/check_pkg
}

[ "$Tiger_Check_ACCOUNTING" != 'N' ] && {
  skip_check $SYSTEMDIR/check_accounting || $SYSTEMDIR/check_accounting
}

[ "$Tiger_Check_INETD" != 'N' ] && {
  skip_check $SYSTEMDIR/check_inetd || $SYSTEMDIR/check_inetd
}
